apiVersion: v1
kind: Service
metadata:
  name: my-docker-service
spec:
  selector:
    app: my-docker-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
